services:
  mongo:
    image: mongo:6.0
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: .
    container_name: excel_server
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: ${PORT}

  bot:
    build: .
    container_name: telegram_bot
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${MONGO_URI}
      API_BOT: ${API_BOT}
    command: ["node", "dist/bot.js"]

volumes:
  mongo_data: